PREPROCESSING:
  DATA:
    NEVADA:
      STATE_NAME: NV
      UNPROCESSED:
        GEOMETRY:
          DISTRICTS: preprocessing/data/nevada/unprocessed/districts_geo
          PRECINCTS: preprocessing/data/nevada/unprocessed/precincts_geo.geojson
          CENSUS_BLOCKS: preprocessing/data/nevada/unprocessed/cb_geo
        INFORMATION:
          CENSUS_BLOCKS: preprocessing/data/nevada/unprocessed/cb_info.csv
          COUNTY_ELECTION: preprocessing/data/nevada/unprocessed/county_election.xlsx
          COUNTY_NAME_FIPS: preprocessing/data/nevada/unprocessed/county_name_fips.csv
      PROCESSED:
        ENACTED:
          DISTRICTING_NAME: enacted
          CENSUS_BLOCKS: preprocessing/data/nevada/processed/enacted/cb.geojson
          CENSUS_BLOCKS_EDGES: preprocessing/data/nevada/processed/enacted/cb_edges.geojson
          PRECINCTS: preprocessing/data/nevada/processed/enacted/precincts.geojson
          DISTRICTS: preprocessing/data/nevada/processed/enacted/districts.geojson
          DISTRICTING: preprocessing/data/nevada/processed/enacted/districting.geojson
    WASHINGTON:
      GEOMETRY:
        DISTRICTS: preprocessing/data/washington/unprocessed/districts_geo
        PRECINCTS: preprocessing/data/washington/unprocessed/precincts_geo.geojson
        CENSUS_BLOCKS: preprocessing/data/washington/unprocessed/cb_geo
      INFORMATION:
        CENSUS_BLOCKS: preprocessing/data/washington/unprocessed/cb_info.csv
        COUNTY_ELECTION: preprocessing/data/washington/unprocessed/county_election.xlsx
        COUNTY_NAME_FIPS: preprocessing/data/washington/unprocessed/county_name_fips.csv
    ARKANSAS:
DATABASE:
  USERNAME: Mavericks
  PASSWORD: changeit
  HOST: 130.245.9.217
  PORT: 3306
  DB: Mavericks
