
ARKANSAS:
  DISTRICTS_GEO_PATH: districts_geo
  CB_GEO_PATH: cb_geo
  CB_INFO_PATH: cb_info.csv
  PRECINCTS_GEO_PATH: precincts_geo.geojson
  PRECINCTS_ELECTION_PATH: election_data.geojson
  PRECINCTS_PATH: precincts.geojson
  ENACTED_ID: 6
  CB_PATH: cb.geojson
  COUNTY_GEO: county_geo

DATABASE:
  USERNAME: Mavericks
  PASSWORD: changeit
  HOST: 130.245.9.217
  PORT: 3306
  DB: Mavericks
